/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OfonoAssistedSatelliteNavigation -p ofonoassistedsatellitenavigation -N ofono_assisted_satellite_navigation.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef OFONOASSISTEDSATELLITENAVIGATION_H_1368991021
#define OFONOASSISTEDSATELLITENAVIGATION_H_1368991021

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.ofono.AssistedSatelliteNavigation
 */
class OfonoAssistedSatelliteNavigation: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ofono.AssistedSatelliteNavigation"; }

public:
    OfonoAssistedSatelliteNavigation(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OfonoAssistedSatelliteNavigation();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> RegisterPositioningRequestAgent(const QDBusObjectPath &in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("RegisterPositioningRequestAgent"), argumentList);
    }

    inline QDBusPendingReply<> SendPositioningElement(const QString &in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("SendPositioningElement"), argumentList);
    }

    inline QDBusPendingReply<> UnregisterPositioningRequestAgent(const QDBusObjectPath &in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("UnregisterPositioningRequestAgent"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

#endif
