/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OfonoPositioningRequestAgent -p ofonopositioningrequestagent ofono_positioning_request_agent.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef OFONOPOSITIONINGREQUESTAGENT_H_1368991021
#define OFONOPOSITIONINGREQUESTAGENT_H_1368991021

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.ofono.PositioningRequestAgent
 */
class OfonoPositioningRequestAgent: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ofono.PositioningRequestAgent"; }

public:
    OfonoPositioningRequestAgent(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OfonoPositioningRequestAgent();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> Release()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Release"), argumentList);
    }

    inline QDBusPendingReply<> Request(const QString &in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("Request"), argumentList);
    }

    inline QDBusPendingReply<> ResetAssistanceData()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("ResetAssistanceData"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace ofono {
    typedef ::OfonoPositioningRequestAgent PositioningRequestAgent;
  }
}
#endif
