/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OfonoVoiceCall -p ofonovoicecall -N ofono_voice_call.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef OFONOVOICECALL_H_1358103518
#define OFONOVOICECALL_H_1358103518

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.ofono.VoiceCall
 */
class OfonoVoiceCall: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ofono.VoiceCall"; }

public:
    OfonoVoiceCall(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OfonoVoiceCall();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> Answer()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Answer"), argumentList);
    }

    inline QDBusPendingReply<> Deflect(const QString &in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("Deflect"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> GetProperties()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetProperties"), argumentList);
    }

    inline QDBusPendingReply<> Hangup()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Hangup"), argumentList);
    }

    inline QDBusPendingReply<> SetProperty(const QString &in0, const QDBusVariant &in1)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0) << QVariant::fromValue(in1);
        return asyncCallWithArgumentList(QLatin1String("SetProperty"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void DisconnectReason(const QString &in0);
    void PropertyChanged(const QString &in0, const QDBusVariant &in1);
};

#endif
