/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OfonoSmartMessagingAgent -p ofonosmartmessagingagent -N ofono_smart_messaging_agent.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef OFONOSMARTMESSAGINGAGENT_H_1358101124
#define OFONOSMARTMESSAGINGAGENT_H_1358101124

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.ofono.SmartMessagingAgent
 */
class OfonoSmartMessagingAgent: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ofono.SmartMessagingAgent"; }

public:
    OfonoSmartMessagingAgent(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OfonoSmartMessagingAgent();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> ReceiveAppointment(const QByteArray &in0, const QVariantMap &in1)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0) << QVariant::fromValue(in1);
        return asyncCallWithArgumentList(QLatin1String("ReceiveAppointment"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> ReceiveBusinessCard(const QByteArray &in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("ReceiveBusinessCard"), argumentList);
    }

    inline QDBusPendingReply<> Release()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Release"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

#endif
