/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OfonoHandsfreeAudioAgent -p ofonohandsfreeaudioagent -N ofono_handsfree_audio_agent.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef OFONOHANDSFREEAUDIOAGENT_H_1368911373
#define OFONOHANDSFREEAUDIOAGENT_H_1368911373

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.ofono.HandsfreeAudioAgent
 */
class OfonoHandsfreeAudioAgent: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ofono.HandsfreeAudioAgent"; }

public:
    OfonoHandsfreeAudioAgent(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OfonoHandsfreeAudioAgent();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> NewConnection(const QDBusObjectPath &in0, const QDBusUnixFileDescriptor &in1, uchar in2)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0) << QVariant::fromValue(in1) << QVariant::fromValue(in2);
        return asyncCallWithArgumentList(QLatin1String("NewConnection"), argumentList);
    }

    inline QDBusPendingReply<> Release()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Release"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

#endif
