/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OfonoPhonebook -p ofonophonebook -N ofono_phonebook.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef OFONOPHONEBOOK_H_1357940298
#define OFONOPHONEBOOK_H_1357940298

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.ofono.Phonebook
 */
class OfonoPhonebook: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ofono.Phonebook"; }

public:
    OfonoPhonebook(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OfonoPhonebook();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> Import()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Import"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

#endif
